### ISSUE TITLE
Is it possible to render more than one at a time?

### ISSUE THREAD

**Issue by jakehockey10** [AndiDittrich/Node.CLI-Progress#10]
I'd like to be able to show multiple progress bars at once.  For example, an overall progress bar and a subtask progress bar would really help.  Is this possible with this library or another one you can think of?

**Comment by AndiDittrich** [comment]
its currently not possible. `cli-progress` does currently only modify a single line of the output.
creating multiple bars at once requires some larger changes of the codebase, sry!

br, Andi

**Comment by jakehockey10** [comment]
No apologies needed!  Thanks for considering!  Any chance this will be worked on in the near future?  If not, feel free to close the issue!

**Comment by AndiDittrich** [comment]
Not in the near future...sry
In case more users request this feature i will implement it. But currently i have not enough time to refactor the whole codebase.

best regards, Andi

**Comment by jakehockey10** [comment]
No one REALLY has time to refactor an entire codebase ;-)

I appreciate your work!

**Comment by EvanK** [comment]
As this is one of the few progress bar packages on npm still being maintained, rendering multiple bars would be a killer feature!

Thanks for the contribution of this project, regardless 😁

**Comment by AndiDittrich** [comment]
Multiprogress has been added to `v3.0.0`

![multibar](https://user-images.githubusercontent.com/1474107/62832209-37f61300-bc2b-11e9-9405-afd2672dc988.png)
