### ISSUE TITLE
a 0 total default to 100

### ISSUE THREAD

**Issue by jfmmm** [AndiDittrich/Node.CLI-Progress#11]
if you put 0 as the total it will show as 100 (sometime you don't want to change the logic but just happen to have nothing to insert in the db that particular time.)

```
var cliProgress = require("cli-progress")
const pb = new cliProgress.Bar();
pb.start(0, 0);
```

will show

`progress [----------------------------------------] 0% | ETA: nulls | 0/100`

instead of 

`progress [----------------------------------------] 0% | ETA: nulls | 0/0`

**Comment by AndiDittrich** [comment]
HI Jean,
thanks for your report. this behaviour is not intended...it is caused by some default values which take precedence in case the provided values are invalid (for example 0).

```js
this.value = startValue || 0;
this.total = total || 100;
```

i could an an about condition like `startValue===total` to the `.start()` function which immediately returns in such cases.

what do you think ?

best regards, Andi

**Comment by AndiDittrich** [comment]
thats a good, suggestion! i think we can do this without any backward compatibility issue.

**Comment by AndiDittrich** [comment]
please try the latest version from the master branch.

**Comment by jfmmm** [comment]
Oh wow glad you got it despite that ridiculous line of code I wrote.. Never write code in a rush before a meeting. Wasn't even the right value haha.

Anyway I just tried it and it work perfectly. It even get completed when I call `.stop()`.

Thanks and have a 🌠 for your trouble :)

**Comment by jfmmm** [comment]
You plan on releasing the new version when? seem like haven't done that in a while, the official one is still 1.3.0.

**Comment by AndiDittrich** [comment]
HI Jean,

thats not correct. The GitHub as well as the related NPM release are pointed to **v1.4.1** (since 4 month).

I will release v1.5.0 today :)

**Comment by jfmmm** [comment]
On github it seem the latest version is still 1.3.0 no? or I'm I misreading this.
http://i.imgur.com/kp1kNbW.png

Anyway npm is updated and that's all I needed, thanks!

**Comment by AndiDittrich** [comment]
Click on **show 4 newer tags** on the top of the last drafted release

**Comment by erikkallen** [comment]
This issue still remains in 1.5.0 because of this line  https://github.com/AndiDittrich/Node.CLI-Progress/commit/7605d2cd0713c1b05397d4f0edb7eabc8cc5a3d8#diff-cd4284509ea6de13aeaac4abc9e81bbdR75 please reopen this issue
