### ISSUE TITLE
Progress bar duplicated on command line

### ISSUE THREAD

**Issue by mmcintyre123** [AndiDittrich/Node.CLI-Progress#12]
I have no other output going to the console, no new lines being printed, starting the bar only once and incrementing the progress with bar.increment(1), yet the bar is being repeatedly printed on the command line making it look very unsightly.  See image below.

![image](https://user-images.githubusercontent.com/12388285/30017081-ba7d47f4-9125-11e7-99de-99bdcc5d8f5d.png)

The same thing happens when I run the demo in the node_modules/cli-progress folder:

![image](https://user-images.githubusercontent.com/12388285/30017276-8cafb37e-9126-11e7-8d13-edf48481f1aa.png)

Running in Git Bash on Windows 10.

**Comment by AndiDittrich** [comment]
Hi mmcintyre123,

i cannot reproduce your issue on Win10/GitBash - it seems that in your case the ANSI sequences which controls the cursor position got ignored. Did you set some terminal options manually ?

**Example**

![git_bash](https://user-images.githubusercontent.com/1474107/30017951-5d391aec-915b-11e7-8b03-cd6f90545757.png)

best regards, Andi

**Comment by mmcintyre123** [comment]
Hi Andi, 
I did some investigating, it seems like it has something to do with the updating numbers (percent, eta, and in my case also duration) confusing ANSI.  Could it have something to do with a disconnect between the rate at which ANSI gets the cursor position and the bar options like fps?  I tried each of these formats:

```
format: 'Getting counts... ' + '|{bar}|'.magenta.bgWhite + ' {percentage}% | ETA: {eta}s | Completed: {value}/{total} | Duration: {duration_formatted}'
format: 'Getting counts... ' + '|{bar}|'.magenta.bgWhite + ' {percentage}% | ETA: {eta}s | Completed: {value}/{total}'
format: 'Getting counts... ' + '|{bar}|'.magenta.bgWhite
```

only the last one prevented the issue.  Here are my current options:

```
var bar = new progress.Bar({
	stopOnComplete: true,
	format: 'Getting counts... ' + '|{bar}|'.magenta.bgWhite + ' {percentage}% | ETA: {eta}s | Completed: {value}/{total} | Duration: {duration_formatted}',
	barCompleteChar: '\u2588',
	barIncompleteChar: '\u2591',
	fps: 5,
	barsize: 50,
	etaBuffer: 10
});
```

I tried fps and etaBuffers up to 50 each and it seems like a higher value makes the problem worse, although it's not a lot different.  The only thing that prevents it completely is disabling all of the counters (percent, eta, etc.).  I didn't change any of the terminal options and also tried in cmd.exe and had the same issue.  Very strange...

**Comment by mmcintyre123** [comment]
Also I should say sometimes the problem doesn't happen at all - though in my case that's rare, 95% of the time it does happen.  So I'm guessing it has to be something like the timing of ansi vs the bar refresh rate.

**Comment by mmcintyre123** [comment]
Actually I think I partly fixed or at least improved it!  In my terminal I had set the cursor to "blinking", I turned that off and it is much better now.  However it still duplicates a bit when the tests start and stop.

**Comment by AndiDittrich** [comment]
does the error only occur with **GitBash** on windows or even on other shells like**PowerShell**, **Bash**, **ZSH** .. ?

**Comment by mmcintyre123** [comment]
I tried it in GitBash on a different computer and it works fine there, very strange.  I'll try reinstalling it on the original computer.  Closing for now, thanks!
