### ISSUE TITLE
Progressbar cannot be initialized to 0

### ISSUE THREAD

**Issue by erikkallen** [AndiDittrich/Node.CLI-Progress#13]
If the progressbar is initialized with a value of 0 it will instead be 100%

    bar.start(1,0.0) // -> results in 100% progress

The problem is this line of code

https://github.com/AndiDittrich/Node.CLI-Progress/blob/master/lib/Bar.js#L75

I will try to make a pull request if I have time if someone needs a workaround for the time beeing use a near 0 value as initial value

bar.start(1,0.00001)

**Comment by mmcintyre123** [comment]
I also have this problem.  Thank you for fixing this!
