### ISSUE TITLE
example

### ISSUE THREAD

**Issue by resigned** [AndiDittrich/Node.CLI-Progress#24]
a real-world example using a CURL request or something and showing the upload progress with legitimate information would be very helpful ;)

**Comment by AndiDittrich** [comment]
hmm.. take a look on [the projects](https://www.npmjs.com/browse/depended/cli-progress) which are using cli-progress - e.g. [ffmpeg-progressbar-cli](https://www.npmjs.com/package/ffmpeg-progressbar-cli)
