### ISSUE TITLE
not-TTY

### ISSUE THREAD

**Issue by ekifox** [AndiDittrich/Node.CLI-Progress#25]
Can you add some functional to your module to support not-TTY prints?
Maybe setInterval with printing simple percent of completed jobs every 30 sec?
I can't see progress of my jobs from Docker logs...

**Comment by AndiDittrich** [comment]
maybe...but generally cli-progress is designed to work in tty environments only - most people don't like a lot of status spam in their logs. 

if more than 10 people request this feature i will implement it (requires some larger changes..)

in the meantime you can simply create a wrapper around cli-progress

best regards, Andi

**Comment by feed4rz** [comment]
+1

**Comment by rvalitov** [comment]
I use PHPStorm and I also don't see any progress bar in the log window:
![image](https://user-images.githubusercontent.com/16267156/49434604-d4226d00-f7b4-11e8-88d2-effd0ca13720.png)

I agree that too much output would be annoying, but it's OK to print just some information, at least the start of progress and the end of progress on the same line, or if it's impossible to print on the same line, then use 2 lines of text maximum, at least in this case it's possible to see what's going on (start and end of task/progress). Meanwhile I will have to use a wrapper.

And thank you for this great lib!

**Comment by kbzowski** [comment]
+1. 
Really annoying to not see progress in WebStorm.

**Comment by AndiDittrich** [comment]
@kbzowski 

it should work in terminal but not in run tasks (see JetBrains Help)

**Comment by rvalitov** [comment]
@AndiDittrich 

So do you mean that if I run it from terminal tab then it should work?

![image](https://user-images.githubusercontent.com/16267156/52260099-12174b00-2936-11e9-8dd6-ff61ac41d4e4.png)

**Comment by AndiDittrich** [comment]
of course - the "Run" tab is not intended to be used as terminal (as JetBrains said...)

**Comment by rvalitov** [comment]
@AndiDittrich 
Thank you! Indeed it works in the Terminal tab.

**Comment by richdunajewski** [comment]
+1

Other progress bar modules work with WebStorm, and I was hoping to switch to this one. We run a lot of scripts where the progress is useful, and I run them from within the editor. Faster to rerun while coding than to switch to the terminal tab and rerun the command.

**Comment by Nox-404** [comment]
+1 I could really use that feature too, having a render only once a bar is stopped could do the trick
It could report the elapsed time since the beginning and the {value}/{total} (maybe another format like nonTTYFormat or something)

**Comment by AndiDittrich** [comment]
the feature is comming in v3.1.0

two options will be available to control the behaviour

```js
{
    // enable output on non tty environments
    noTTYOutput: true,

    // 10s update interval
    notTTYSchedule: 100000
}
```

in noTTY mode, all terminal control sequences will be disabled and the progress bar output will be generated with the given schedule (notTTYSchedule).

synchronous updates are not supported

**Comment by AndiDittrich** [comment]
notty support has been added to the master branch 

**i appreciate your feedback** before releasing it
