### ISSUE TITLE
no output on windows GitBash

### ISSUE THREAD

**Issue by beenotung** [AndiDittrich/Node.CLI-Progress#33]
I'm using the default setting on windows 10 with GitBash. There is no output showing the progress. The same settings works on archlinux.

**Comment by AndiDittrich** [comment]
HI  @beenotung 

"git bash" doesn't emulate/open a TTY by default (same issue on docker and other tools).
use Windows PowerShell or add the wrapper `winpty` in front of your command

best regards, Andi
