### ISSUE TITLE
MultiBar doesn't stop when all bars complete

### ISSUE THREAD

**Issue by Nox-404** [AndiDittrich/Node.CLI-Progress#36]
With the stopOnComplete option, the multibar doesn't stop when all child bars complete.
I already made a PR if you want to review it !35

**Comment by AndiDittrich** [comment]
stopOnComplete is currently only implemented for the SingleBar - i will review your pull request soon

**Comment by leodutra** [comment]
@Nox-404 please take a look on https://github.com/AndiDittrich/Node.CLI-Progress/issues/47...
Maybe you had the same issue...?

**Comment by AndiDittrich** [comment]
@leodutra `stopOnComplete` was not yet implemented in the initial 3.0.0 release for the multibar

**Comment by leodutra** [comment]
Hum, yeah I saw that. But at least it stops the internal bars on time.
Anyways, I cannot stop manually the multibar because it is the manager for bars of any other `downloadFile()` call.
