### ISSUE TITLE
Enhancement: Optional callback when multibar completes

### ISSUE THREAD

**Issue by welljsjs** [AndiDittrich/Node.CLI-Progress#39]
This is a feature request.

The new multibar is great and provides some new possibilities. However, it'd be even greater if there was an optional callback method that is called when the multibar stops or when all single bars included in the multibar have finished, respectively.

This would be incredibly helpful because one wouldn't have to iterate over all bars to see if they're active or not.

**Comment by AndiDittrich** [comment]
hi @welljsjs 

i fully understand your intention but you might using cli-progress in a wrong way: it is designed as **pure ui componenten** and not as kind of task queue.

program logic and ui components should always be separated...otherwise your program might hang because of the ui component...

**Comment by welljsjs** [comment]
Alles klar, das stimmt. Danke.
