### ISSUE TITLE
pr: suggestion for enhancement of the Bar class

### ISSUE THREAD

**Issue by yigal-dayan2** [AndiDittrich/Node.CLI-Progress#41]
The progress bar class is specifically designed for output to tty terminals, using cursor moves to display the bar as it progresses. When running inside a docker it is disabled.

In single bar mode only, it is easy to enhance the class so that it works with non-tty terminals.

1. Remove the line that checks for this.terminal.isTTY()
2. Replace code that sets the cursor at start on line:
        this.terminal.cursorTo(0, null);
   with code that backspaces lastDrawnString.length characters, for example:
       const back = new Array(this.lastDrawnString.length + 1).join( '\x08' );
       this.terminal.write(back);

We made this change and now see the progress bar in running docker containers.

**Comment by AndiDittrich** [comment]
HI @yigal-dayan2 

please read the v3.1 changelog: https://github.com/AndiDittrich/Node.CLI-Progress/blob/master/CHANGES.md - noTTY mode has been implemented for such use cases

**Comment by yigal-dayan2** [comment]
The v3.1 implementation seems to add a new line rather than do backspaces in the same line. The bar is not being overwritten but is duplicated with modifications on consecutive lines.

**Comment by AndiDittrich** [comment]
of course...this is the only "cross environment" solution...

**Comment by yigal-dayan2** [comment]
I see... so you don't see a need to provide for this explicit scenario (running docker in a terminal).
We thought it's useful enough to have a dedicated option, but we may be wrong.

**Comment by yigal-dayan2** [comment]
thanks, closing the issue
