### ISSUE TITLE
Add option to have fix with duration and ETA

### ISSUE THREAD

**Issue by BenjD90** [AndiDittrich/Node.CLI-Progress#44]
Hello,

I'm using the multi bar progress bar, and it's working good.
I have an idea, to add some options (2 I think) to fix the width of the ETA and the duration. To apply it to the formatted type seems to be the good use case.

I think this option would be used here : https://github.com/AndiDittrich/Node.CLI-Progress/blob/c60f1e51c3a8d7674f3f3ea027956055ecc5f682/lib/generic-bar.js#L144

What do you think about that ?

Benjamin

**Comment by BenjD90** [comment]
Some padding left to the percentage would be great too :smiley: 

Here what I get :
![Peek 2019-09-28 21-42](https://user-images.githubusercontent.com/8216338/65821673-e5070800-e238-11e9-9fb6-6889c6a43483.gif)

**Comment by AndiDittrich** [comment]
Hi @BenjD90 ,

maybe a "generic" format callback function which allows users to add custom paddings/fixed widths on their own ?

**Comment by BenjD90** [comment]
yes, that would be nice, I'll try to do a PR today ;)

**Comment by AndiDittrich** [comment]
please take a look on fa630e3a359525bb07c3f738034ba053b8b16a97

i've added custom formatter support by allowing to pass a custom callback function as `options.format`

**Comment by BenjD90** [comment]
@AndiDittrich  Seems good to me :)
Could you release it ? (it seems to be v 3.3.0)

**Comment by AndiDittrich** [comment]
it requires some additional tests + docs

**Comment by AndiDittrich** [comment]
`v3.3.0` has been released
