### ISSUE TITLE
Visual queue if a bar is stopped below 100%

### ISSUE THREAD

**Issue by oa998** [AndiDittrich/Node.CLI-Progress#46]
Could an option be added to pass a 'failure color'?

If `stop()` is invoked and the `current` !== `total`, redraw the bar once again with the "failed color" instead of the normal color to highlight the process that did not meet expectations.

Example: Third bar was for a process that failed on 1 execution and I'm looking to make it more apparent for my use-case.

![image](https://user-images.githubusercontent.com/21143866/65845342-e2bfaf00-e307-11e9-8aca-83ac1c25ff5d.png)

I'll try to find a way to solve this and submit a PR if it can be done cleanly.

**Comment by oa998** [comment]
Closing this issue. It was not reasonable to have 2 different format strings in the _formatter
Easier to override from my side.

![image](https://user-images.githubusercontent.com/21143866/65847062-fec64f00-e30d-11e9-860c-1db0321d7901.png)

Great library. Keep up the good work.

**Comment by AndiDittrich** [comment]
v3.3.0 intorduces custom formatters - it's very easy to customize the output.

i'll release it soon

**Comment by AndiDittrich** [comment]
`v3.3.0` has been released

## Example ##

```js
const _progress = require('../cli-progress');
const _colors = require('colors');

function myFormatter(options, params, payload){

    // bar grows dynamically by current progrss - no whitespaces are added
    const bar = options.barCompleteString.substr(0, Math.round(params.progress*options.barsize));

    // end value reached ?
    // change color to green when finished
    if (params.value >= params.total){
        return '# ' + _colors.grey(payload.task) + '   ' + _colors.green(params.value + '/' + params.total) + ' --[' + bar + ']-- ';
    }else{
        return '# ' + payload.task + '   ' + _colors.yellow(params.value + '/' + params.total) + ' --[' + bar + ']-- ';
    }    
}

function Example5(){
    console.log('');
    // create new progress bar
    const b1 = new _progress.Bar({
        format: myFormatter,
        barCompleteChar: '\u2588',
        barIncompleteChar: '\u2591',
        hideCursor: true,
        stopOnComplete: true
    });

    // initialize the bar -  defining payload token "speed" with the default value "N/A"
    b1.start(200, 0, {
        task: 'Task 1'
    });

    // 20ms update rate
    const timer = setInterval(function(){
        // increment value
        b1.increment();

        // finished ?
        if (b1.isActive === false){
            clearInterval(timer);
        }
    }, 20);
}

Example5();
```
