### ISSUE TITLE
[Feature request] Allow multicolor progress bars

### ISSUE THREAD

**Issue by ehmicky** [AndiDittrich/Node.CLI-Progress#53]
This would be great if the "complete" part of the progress bar could be of a different color than the "incomplete" part of it.

Using ANSI color escapes in the `barCompleteChar` or `barIncompleteChar` options does not currently work because the values for those options must currently be 1 character long. Using colors in those options make the progress bar shorter and jump left and right.

(Note that it is possible though to give a color to the whole bar as the `shades_grey` preset shows.)

**Comment by AndiDittrich** [comment]
use a custom formatter

**Comment by ehmicky** [comment]
@AndiDittrich What about improving the default formatter instead?

I believe all that is needed is to replace `string.substr()` by [`slice-ansi`](https://github.com/chalk/slice-ansi) in the following three lines: https://github.com/AndiDittrich/Node.CLI-Progress/blob/master/lib/formatter.js#L30-L34.

**Comment by AndiDittrich** [comment]
generally the dependencies should be reduced to `zero` in the near future - it's a big problem to audit each dependency...therefore i won't add any new libraries (it is not neccessary to achive your goal).

**Comment by ehmicky** [comment]
Alright, no worries!

**Comment by AndiDittrich** [comment]
whats about an option like "barGlue" ? that's the easiest way to add custom colors for each sub-bar

**Comment by ehmicky** [comment]
Sure that works. However I would not go for a PR for this anymore. Thanks for the help though!

**Comment by AndiDittrich** [comment]
the `barGlue` option has been added to the master branch (upcoming v3.6)

**Comment by ehmicky** [comment]
Thanks!
