### ISSUE TITLE
Bar formatting: payload value 0 appears as '{'

### ISSUE THREAD

**Issue by Nisanez** [AndiDittrich/Node.CLI-Progress#55]
Hi,

I am using the bar formatting to display thread number. When the payload value is 0 i am getting the curly brackets sign '{' instead of the number 0. with other numbers it prints correctly. 

Example:
The format string:
`"format: '{thread} | {bar}' + '| {percentage}/100%'"`

The progress creation command:
`progressBar: multibar.create( 100, 0, {thread: 0}),`

The result I am getting is:
`{ | ========================================| '100/100%`
..^
Any idea how can I solve this issue?

Thanks!

**Comment by AndiDittrich** [comment]
it's fixed within the master branch

**Comment by Nisanez** [comment]
> it's fixed within the master branch

Thanks!

**Comment by AndiDittrich** [comment]
v3.4.0 is published including the fixes
