### ISSUE TITLE
Override MultiBar format in each SingleBar

### ISSUE THREAD

**Issue by jgalrito** [AndiDittrich/Node.CLI-Progress#62]
Is there anyway to override the MultiBar options format for a particular SingleBar? In my case I want to show a "total" progress bar that aggregates the progress from the others

**Comment by AndiDittrich** [comment]
use a [custom formatter](https://github.com/AndiDittrich/Node.CLI-Progress#custom-formatters)

**Comment by jgalrito** [comment]
The goal was to do it easily using a template but I can just return the default formatter with different options inside the custom one.  Thanks

**Comment by bentorkington** [comment]
@AndiDittrich I accept that using custom formatters is workable for this, but it feels like it creates more effort that it needs to, stuffing extra data in the metadata object so the custom formatter knows which template to use.

Would it be possible for MultiBar.create to accept an optional `options` override for special 'overall' bars like this?

**Comment by AndiDittrich** [comment]
it's possible...but atm i didn't have any resources to implement such "special" cases. sry

**Comment by bentorkington** [comment]
Thanks for the fast response Andi :)
