### ISSUE TITLE
[Enhancement] Easy way to update the ETA of Bars

### ISSUE THREAD

**Issue by BigBrainAFK** [AndiDittrich/Node.CLI-Progress#65]
I have not found a simple way to update the ETA value of a bar except for doing this
```js
setInterval(() => {
	if (progBar.isActive) progBar.update(progBar.value);
}, 1000);
```
where `progBar` is an instance of the `SingleBar` class.

I have tried using the `<Bar>.render()` method and `<Bar>.update(0)` (which just resets the bar every time).

This is only a problem when the script solely relies on `<Bar>.increment()` and does not count the current value itself. If the script does count the current value itself one can simply use `<Bar>.update(value)`

**Comment by AndiDittrich** [comment]
i don't understand the issue: the ETA value is automatically calculated and cannot be altered. if you want to use a different algorithm please use the payload feature to add custom values

**Comment by BigBrainAFK** [comment]
the problem i have is that i have no use for a bar that only updates the eta when the bar actually has an increment of at least 1

**Comment by AndiDittrich** [comment]
the eta calculation wont work in case all values are identically (long running processes) - your code above will cause this behaviour `vt_rate=0` and therefore the eta will set to `INF`

**Comment by BigBrainAFK** [comment]
so the calculation does work cause its a valid estimate. and its better than being stuck at the last time the value got updated

**Comment by AndiDittrich** [comment]
it's only an edge case that it works for you....cli progress eta calculation is not designed for extreme long running processes.

if you like i can add an additional method like `updateETA` which can be triggered externally

**Comment by BigBrainAFK** [comment]
would be practical. and my example was admittedly chosen as an exaggerated edge case but in my use case of a 2minute runnibg process it aso look like the script hangs every now and then due to the eta not refreshing. it would be nice to have a method to uodate the eta

**Comment by AndiDittrich** [comment]
i've added two new features to the master branch:

* method `updateETA` to force an eta update using the current value
* option `etaAsynchronousUpdate` to force an eta update on each asynchronous `render` call - this is related to the `fps` settings - therefore the `fps` rate should be set in conjunction with the eta buffer size:

**Example**

```js
const _progress = require('./cli-progress');
const _terminal = require('./lib/terminal');

// 50s/2 => new value expected within 25s
const p1 = new _progress.SingleBar({
    fps: 2,
    etaBuffer: 50,
    etaAsynchronousUpdate: true
}, _progress.Presets.shades_classic);

p1.start(100, 50);
```

**Comment by designbyadrian** [comment]
I'd be great if the unit was mentioned in the README. It wasn't until here where I understood that the etaBuffer is in seconds!

**Comment by AndiDittrich** [comment]
etaBuffer is NOT is seconds, it's just the buffer size `N`

**Comment by designbyadrian** [comment]
`N` what? Updates? Frames?

**Comment by AndiDittrich** [comment]
size of elements within the buffer

**Comment by designbyadrian** [comment]
When is a new element added to the buffer?

**Comment by AndiDittrich** [comment]
depends on the settings `etaAsynchronousUpdate` - please take a look into the sources. this thread handles a very specific case of continuous eta updates
