### ISSUE TITLE
Mulitline does not work well on windows command prompt

### ISSUE THREAD

**Issue by mannharleen** [AndiDittrich/Node.CLI-Progress#69]
For every update, a new bar is written ie. the original bar is not updated.
Instead of getting one line that updates (code #1), I get a separate line for every update (code #2)

```
code #1 
[Account             ] ████████████████████████████████████████ 100 | Progress=19/19 | Elapsed(s)=5
```

```
code #2
[Account             ] ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1 | Progress=1/100 | Elapsed(s)=0 | ETA(s)=1
[Account             ] ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1 | Progress=1/100 | Elapsed(s)=1 | ETA(s)=1
[Account             ] ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1 | Progress=1/100 | Elapsed(s)=2 | ETA(s)=1
```

node=11
cli-progress=3.8.0
windows=8
terminal=<cmd> Microsoft Windows [Version 6.3.9600]

**Comment by AndiDittrich** [comment]
can you provide a minimal example to reproduce the issue ?
which versions (node, cli-progress, windows) do you use ?

**Comment by mannharleen** [comment]
That was a really quick response! 
I just solved it - I had to increase the screen buffer size of the command prompt.

PS. I am providing some more details on the issue now

**Comment by AndiDittrich** [comment]
the windows command prompt doesn't work as expected. please use the powershell.
since the issue is raised on an old windows version i'm unable to test it - cli-progress is not designed for windows even it may work

generally the window has to be bigger then the number of total progress bars - see #59

**Comment by mannharleen** [comment]
"cli-progress is not designed for windows even it may work" - it would be best mentioned on the README.md then

**Comment by AndiDittrich** [comment]
maybe...but this issue affects any UI component within the standard command prompts on windows

**Comment by AndiDittrich** [comment]
did you tried it with windows powershell on win10 ?

**Comment by mannharleen** [comment]
Same issue with powershell.

**Comment by AndiDittrich** [comment]
it works without any issues...the problem seems to be related to your environment (windows version, powershell version, environment config)

![image](https://user-images.githubusercontent.com/1474107/80687760-14317080-8acb-11ea-90ce-98fc1674a8b0.png)

**Comment by AndiDittrich** [comment]
std windows command prompt ...

![image](https://user-images.githubusercontent.com/1474107/80689008-fbc25580-8acc-11ea-8927-2a0f35c6831c.png)

**Comment by mannharleen** [comment]
Thanks for your responses Andi. I've settled for how it is on Win8. 
It would still help if README mentions that it works as expected on Win10 CMD version etc & above. 

I dont have Win10, so cant verify at my end.

**Comment by AndiDittrich** [comment]
i've already added a "weak" notice about windows platforms: https://github.com/AndiDittrich/Node.CLI-Progress#compatibility

btw. cli-progress is also used in [NodeMCU-Tool](https://github.com/AndiDittrich/NodeMCU-Tool) which doesn't encountered any issue with older windows versions yet - therefore you're observed behaviour is very strange
