### ISSUE TITLE
Invalid percantage on progress 999/1000 => 100%

### ISSUE THREAD

**Issue by OxCom** [AndiDittrich/Node.CLI-Progress#70]
**Example**:
```javascript
import cliProgress from 'cli-progress';

const cli = new cliProgress.SingleBar();

cli.start(1000);
cli.update(999);
```
**Output**:
`progress [========================================] 100% | ETA: 1s | 999/1000`

**Current progress**: 100%
**Expected**: 99%

**Comment by AndiDittrich** [comment]
Hi @OxCom ,

thanks for your feddback.

currently standard [Math.round](https://github.com/AndiDittrich/Node.CLI-Progress/blob/master/lib/formatter.js#L22) is applied to calculate the percentage value. it should be replaced by `Math.floor` to round down to the nearest integer
