### ISSUE TITLE
why use process.stderr as the default stream?

### ISSUE THREAD

**Issue by linxixuan** [AndiDittrich/Node.CLI-Progress#73]
I use single-bar update progress status, but sometimes log will output to one file. So I use isTTY to  judge whether this API should be used.

But I found that only I use stdout as the progress-bar's stream can work. I wonder why process-bar use stderr as default stream?

**Comment by AndiDittrich** [comment]
it gives the possibility to "throw" the "useless" progress away and use stdout for regular logging messages. additionally it doesn't wastes log-files because most users only redirecting the stdout stream.

**Comment by linxixuan** [comment]
THX!
When my scripts runs in a build server, they pipe my progress info to other progress, then 

```js
  // bar is a multibar
  if (!bar.isTTY()) { // false, cause default stream is process.stderr
     bar.increment(1)); // will throw error: call increment of undefined
  }
```
so I change the process-bar instance's stream to process stdout
