### ISSUE TITLE
TypeDefinition Files

### ISSUE THREAD

**Issue by KilianKilmister** [AndiDittrich/Node.CLI-Progress#76]
TypeDefinition Files would be great for this:  
[reference from PR on Fork](https://github.com/KilianKilmister/Node.CLI-Progress/pull/1#issue-441181015)

>  I'm in the process of porting CLI-Progress to TypeScript, I did some preliminary typing and added all the configs but havent touched the source yet. So feel free to make use of them.
> 
> the typing isn't that great right now because i don't quite get how it works in a non ESM environment, but they work for developing.
> 
> If you are interested in moving the project, or part of it to TS, i'll gladly keep you up to date. and i'll certainly file a PR when the Typings are complete

**Comment by AndiDittrich** [comment]
Hi @KilianKilmister ,

contributions for cli-progress are welcome, especially TypeScript type definitions.
in case the type definitions are working as expected and reached stable state you can create a pull request to add them the project.

best regards
