### ISSUE TITLE
start() renders a line, update renders a new line

### ISSUE THREAD

**Issue by kaaljabr** [AndiDittrich/Node.CLI-Progress#77]
When calling start(1000, 0);
it immediately renders a line with progress 0%.
When update() or increment() are called, a new line is rendered and further calls to update or increment will update the 2nd line. And first line stays at 0%.

How can I get only one progress bar?

**Comment by AndiDittrich** [comment]
it sounds like an environment error...try another terminal/nodejs version.
did you tried the examples ?

**Comment by LarsOlt** [comment]
same problem here

**Comment by LarsOlt** [comment]
I just noticed it only happens in Visual Studio Code. Using the external console works. @kaaljabr

**Comment by AndiDittrich** [comment]
Hi @LarsOlt 

i'm unable to reproduce your issue. please provide additional informations (minimal example + os/node/vscode versions)

![cliprogress](https://user-images.githubusercontent.com/1474107/87850565-798a4600-c8f1-11ea-993b-6a937f3af9d8.png)

**Comment by LarsOlt** [comment]
Hello @AndiDittrich, thanks for the help. I am using Cmder as the internal console for vsc. After changing the font inside Cmder it worked. Tested with node 14.5.0 & 12.18.2 

![image](https://user-images.githubusercontent.com/32353679/87851470-5a8fb200-c8f9-11ea-89e4-0d87a5ceae5d.png)

**Comment by AndiDittrich** [comment]
great! i'll mark this issue as resolved

**Comment by kaaljabr** [comment]
I got this issue resolved, I was having start(1000, 0); call made from a different promise than the update function call. Refactored my code and now it works great.
