### ISSUE TITLE
Synchronous Multibar not working

### ISSUE THREAD

**Issue by smamusa** [AndiDittrich/Node.CLI-Progress#79]
When using multibar update within for loops, e.g. : 0 to 10e7 the bars stay at 0,  and then jump to full completition. This works only for Singlebar instances and not multibar ones.

**Comment by AndiDittrich** [comment]
please provide a minimal example for this issue/use case, thanks!

**Comment by smamusa** [comment]
`const progress = require('cli-progress');

const multibar = new progress.MultiBar({
  format: ' {bar} | "{randomBarProgreessName}" | {value}/{total}',
  hideCursor: true,
  barCompleteChar: '\u2588',
  barIncompleteChar: '\u2591',
  stopOnComplete: true,
});

const total1 = 10e4;
const total2 = 10e3;

const b1 = multibar.create(total1, 0);
b1.setTotal(total1);
b1.setTotal(total2);
const b2 = multibar.create(total2, 0);

b1.start();
b2.start();

console.log('App started');

for (let i = 1; i <= total1; i += 1) {
  b1.update(i);
}
for (let i = 1; i <= total2; i += 1) {
  b2.update(i);
}`

Output is bellow, but these bars appear after the for loops are done, this is working fine for the single bar.
![screenshot](https://user-images.githubusercontent.com/49687548/90242541-89804180-de2d-11ea-934f-9500dc65c98c.PNG)

**Comment by AndiDittrich** [comment]
i cannot identify any error: by using a for loop, other async tasks (like the progress updater) are not updated (blocking). additionally your example code runs extremely fast..therefore only one update will be drawn.

btw. you shouldn't call `start()` on multibar instances, it's already done by `create`

**Comment by AndiDittrich** [comment]
i've added an [example](https://github.com/AndiDittrich/Node.CLI-Progress/blob/master/examples/example-synchronous.js#L33) howto enforce a redraw in synchronous context

**Comment by smamusa** [comment]
Thank you for the feedback, forcing the redraw is what I needed.
