### ISSUE TITLE
Create bar in Multibar returns undefined on VSCode

### ISSUE THREAD

**Issue by ildelian** [AndiDittrich/Node.CLI-Progress#83]
Good morning.

```
const cliProgress = require('cli-progress');
const progressBarManager = new cliProgress.MultiBar({
        clearOnComplete: false,
        hideCursor: true,
        forceRedraw: true,
        format: '{threadId} - {threadStatus} | ' + _colors.cyan('{bar}') + ' | {percentage}% | ETA: {eta}s | {value}/{total}'
    }, cliProgress.Presets.shades_grey);

const globalProgressBar = progressBarManager.create(this.config.totalThreads,0, {threadId: "Total Executed Threads", threadStatus: "RUNNING"});
```
I am using VSCODE (1.41.1) on a NodeJS (13.14.0) project.
The above code works in Windows CMD, Windows PowerShell and Git Bash consoles with no problem, but not works on Visual Studio Code "internalConsole", the create method of the bar returns always undefined witho no error asociated.

Kind regards.

**Comment by AndiDittrich** [comment]
i'm unable to reproduce your issue in VS Code - technically your issue sounds very weird because the terminal has nothing to do with the execution of the javascript process - something seems to be absolutely misconfigured within your environment

**Comment by ildelian** [comment]
Hi. I have see where is the problem ().

Visual studio code has three kind of consoles in launch.json config:
internalConsole
integratedTerminal
externalTerminal

I have debugged your library and, in the constructor of the MultiBar class, on the line:

`// store terminal instance
this.terminal = (this.options.terminal) ? this.options.terminal : new _Terminal(this.options.stream);
`

When you select "integratedTerminal" and "externalTerminal" as console in VSCODE, the var "this.options.stream" is type "WriteStream".
When you select "internalConsole" as console in VSCODE, the var "this.options.stream" is type "Socket".

Socket produces a non TTY terminal, so, you simply return false on the create method of MultiBar class.
This is normal because Socket is not capable to use like a TTY Terminal, so, this is not a problem of your library.
