### ISSUE TITLE
Multibar having problems showing up

### ISSUE THREAD

**Issue by jarquafelmu** [AndiDittrich/Node.CLI-Progress#84]
I'm having a problem with MultiBar where SingleBars created with it aren't showing up or only all but the last one shows up. I created a repl.it in order to try and show what is going on. 
https://repl.it/join/pqfvcnhb-jarquafelmu

On line 37 I create a top over all bar and then on line 69 I am creating the sub-bars in order to get an idea of what is happening. Except the subbars aren't showing up. 

I'm not sure what I am doing wrong here

**Comment by AndiDittrich** [comment]
please provide an example here on GitHub or any other service which doesn't require a login

**Comment by jarquafelmu** [comment]
I don't know where to host it that doesn't require a log in and would allow for npm modules

**Comment by AndiDittrich** [comment]
just post a minimal example here

**Comment by GP4cK** [comment]
I had the same issue but I realised that it was because my code was entirely synchronous (I was using fs.statSync). Once I moved to async, the bar showed up.
