### ISSUE TITLE
Integrating logging and the progress bar...

### ISSUE THREAD

**Issue by flynx** [AndiDittrich/Node.CLI-Progress#85]
Hi,

Would be great to be able to integrate logging and a progress bar/multi-bar -- currently I have a need to both show the total progress and print logging/status info while the app is running and in the current implementation it is either non-trivial (undocumented) or I'm missing something...

I see one of two approaches here:
1. a timed callback to be able to print/log something when the cursor is at the top/left.
2. a wrapper around `console.log(..)` and friends, something like `::log(..)`, `::warn(..)`, `::error(..)`

Or for customizability both approaches as it would be trivial to implement №2 via №1.

Thanks!

**Comment by AndiDittrich** [comment]
Such use-case is not supported yet, sry.

you can find some related issues/feature request but i didn't see an possibilities to implement it in the current release

**Comment by AndiDittrich** [comment]
https://github.com/AndiDittrich/Node.CLI-Progress/pull/57

**Comment by flynx** [comment]
My bad, I seem to have missed the smallest section in the docs, thanks for the tip... 

Looks to be exactly what I need, will investigate, Thanks!

**Comment by bentorkington** [comment]
@flynx which section was this, please? I need to do the same thing, and can't find anything in `README.md` that looks like it would help

**Comment by AndiDittrich** [comment]
see the referenced pull request above and event docs: https://github.com/AndiDittrich/Node.CLI-Progress/blob/master/docs/events.md
