### ISSUE TITLE
listing folder with bracket return empty array

### ISSUE THREAD

**Issue by thib3113** [AndiDittrich/Node.CLI-Progress#90]
It seems that we can't list a folder with bracket .

It's maybe a limitation of the FTP protocol . On my side, escaping the brackets with a backslash is enough, but I found no documentations about it .

I doesn't test others functions with a bracket

version : 4.6.3

**Comment by AndiDittrich** [comment]
Hi @thib3113 

i believe you've posted the issue to the wrong project/repository

**Comment by thib3113** [comment]
oh ... yes ... fail ... sorry ...
