### ISSUE TITLE
Make ETA choose appropriate time unit

### ISSUE THREAD

**Issue by reidrivenburgh** [AndiDittrich/Node.CLI-Progress#91]
I like that you have an ETA parameter, but I'm using this for a job that will take over a day to run.  It'd be nice if you chose a suitable unit for the ETA display, like hours, minutes, or seconds.  Thank you!

**Comment by AndiDittrich** [comment]
use a custom formatter and/or custom payloads

**Comment by reidrivenburgh** [comment]
I hadn't seen {eta_formatted}, sorry.  I'm trying it now.

**Comment by paul-uz** [comment]
@reidrivenburgh what was your final solution?

**Comment by reidrivenburgh** [comment]
@paul-uz This was so long ago, and on a project I no longer work on, that I don't remember, sorry.  I'm assuming I was able to make use of {eta_formatted}.
