### ISSUE TITLE
Add Types for TypeScript

### ISSUE THREAD

**Issue by wschwab** [AndiDittrich/Node.CLI-Progress#94]
Hey! This is a really awesome package! I just wanted to throw up an issue for a potential improvement to throw in `types` for TypeScript projects. I figured I'd link to what I figure might be useful resources:

- [example PR to add types to an exisiting JS module](https://github.com/konvajs/vue-konva/pull/54)
- [article on adding types to JS packages](https://medium.com/jspoint/typescript-type-declaration-files-4b29077c43) (watch out, it's a Premium article)
- [article on adding types](https://www.credera.com/insights/typescript-adding-custom-type-definitions-for-existing-libraries/)

Cheers!

**Comment by wschwab** [comment]
lol, I missed that it was already there, closing

Thanks for this package!

**Comment by AndiDittrich** [comment]
it's currently provided via https://www.npmjs.com/package/@types/cli-progress
