### ISSUE TITLE
Updates sometime creates 2 lines in the console

### ISSUE THREAD

**Issue by Allain55** [AndiDittrich/Node.CLI-Progress#95]
Hi,
after running this:
```
		const bar1 = new cliProgress.SingleBar({}, cliProgress.Presets.shades_classic);

		bar1.start(100, 0);

		setTimeout(() => {
			bar1.update(100);
			bar1.stop();
		}, 1000)
```
		
		
I get 2 lines: 1 with 0% and 1 with 100%

		
This example with smaller delay works fine:
```
		const bar1 = new cliProgress.SingleBar({}, cliProgress.Presets.shades_classic);

		bar1.start(100, 0);

		setTimeout(() => {
			bar1.update(100);
			bar1.stop();
		}, 600)
		
```

But if I add a sync update to it I get 2 lines again:
```
		const bar1 = new cliProgress.SingleBar({}, cliProgress.Presets.shades_classic);

		bar1.start(100, 0);
		bar1.update(50);

		setTimeout(() => {
			bar1.update(100);
			bar1.stop();
		}, 600)
```
		
Note: using a setTimeout with eg. 400ms works again.
Tested with Node v14.11 and 15.5.1
OS: Ubuntu 16.04.7 LTS

**Comment by AndiDittrich** [comment]
Hi @Allain55 

i'm unable to reproduce your issue on debian 10 (xfce4 terminal and vs code)

**Comment by Allain55** [comment]
Ahh I had a console.log after start and before update that caused it. Thanks for checking it!
