### ISSUE TITLE
Multi Bar Mode: add option for console text output

### ISSUE THREAD

**Issue by jumoog** [AndiDittrich/Node.CLI-Progress#99]
It would be cool to have a text output option for every new MultiBar(). Right now a console.log interruptes the progressbars. So my idea was to have a fixed line where you can output text.  So its possible to write Text without interrupting progressbars. Something like multibar.log()

**Comment by AndiDittrich** [comment]
please take a look into the other related issues, it's a repeating feature request

**Comment by Darkproduct** [comment]
See #57
